apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
# no of replicas needed
  replicas: 3
  selector:
    matchLabels:
  # these are the labels replica set uses to create pod replicas, this should match pod replicas
      purpose: deployment-demo
      project: roboshop
      app: nginx
    # this is pod defination
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx    
          